---
title: Adaptive Content with Evidence-Based Diagnosis (ACED)
---


ACED was an NSF sponsored assessment "for" learning system that had the following features:

* [ACED Model](Model.qmd) was constructed using Evidence-centered assessment design methodology.

* [Proficiency](PM.qmd) based on expert analysis of domain (Algebraic sequences).

* [Q-Matrix](QMatrix.qmd) was augmented to included prior opinion about item difficulty.

* [Accessibility] -- Tasks were designed to be presented either on-screen or in special touch-graphics mode for persons with low visual acuity.

* [Elaborated task-specific feedback] was available for all items.

* [Bayesian network scoring engine](BayesNet.qmd)

* [Weight-of-evidence] algorithm for adaptive task selection

* [Evaluation](Evaluation.qmd) a randomized trial with 268 middle school students showed that

  - ACED (with adaptivity and elaborated feedback) produced significant gains between the pre-test and post-test.
  - ACED scores correlated well with post-test scores, and the correlation "'improved'" when elaborated feedback was given.
  
  
This website has the following details about ACED:

* [People](People.qmd) -- Who worked on the project

* [Model](Model.qmd) -- Description of the model.

* [Data](Data.qmd) -- Description of the data collected from the experiment, and how to gain access.

* [Publications](Publications.qmd) -- A list of reports that can provide additional information.

ACED development and data collection was sponsored by National Science Foundation Grant  No. 0313202.
